name: bool_school
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/header.png
    - assets/algebra.png
    - assets/home.png
    - assets/learn.png
    - assets/quiz.png
    - assets/profile.png
    - assets/left-arrow.png
    - assets/right-arrow.png
  uses-material-design: true
